import type { PuzzleLevelDefinition } from './types';

export const DEFAULT_CIRCUIT_LEVEL: PuzzleLevelDefinition = {
  id: 'circuit-5x6',
  name: 'Circuit Repair Simulation',
  rows: 5,
  cols: 6,
  blocked: [
    { x: 0, y: 4 },
    { x: 5, y: 4 },
  ],
  hintCells: [
    { x: 4, y: 0 },
    { x: 1, y: 0 },
    { x: 1, y: 1 },
    { x: 0, y: 1 },
    { x: 0, y: 2 },
    { x: 4, y: 1 },
    { x: 5, y: 1 },
    { x: 5, y: 2 },
    { x: 2, y: 3 },
    { x: 1, y: 3 },
    { x: 1, y: 2 },
    { x: 2, y: 2 },
    { x: 2, y: 1 },
    { x: 3, y: 1 },
    { x: 3, y: 2 },
    { x: 4, y: 2 },
    { x: 4, y: 3 },
    { x: 3, y: 3 },
    { x: 3, y: 4 },
    { x: 2, y: 4 },
  ],
  hintColors: {
    '4,0': '#9ddb22',
    '1,0': '#9ddb22',
    '1,1': '#9ddb22',
    '0,1': '#9ddb22',
    '0,2': '#9ddb22',
    '4,1': '#9ddb22',
    '5,1': '#9ddb22',
    '5,2': '#9ddb22',
    '2,3': '#9ddb22',
    '1,3': '#9ddb22',
    '1,2': '#9ddb22',
    '2,2': '#9ddb22',
    '2,1': '#9ddb22',
    '3,1': '#9ddb22',
    '3,2': '#9ddb22',
    '4,2': '#9ddb22',
    '4,3': '#9ddb22',
    '3,3': '#9ddb22',
    '3,4': '#9ddb22',
    '2,4': '#9ddb22',
  },
  rowTargets: [2, 6, 6, 4, 2],
  colTargets: [2, 4, 4, 4, 4, 2],
  pieces: [
    {
      id: 'p-a',
      name: 'Gamma',
      color: '#9ddb22',
      cells: [
        { x: 0, y: 0 },
        { x: 1, y: 0 },
        { x: 1, y: 1 },
        { x: 2, y: 1 },
      ],
      count: 1,
    },
    {
      id: 'p-b',
      name: 'Hook',
      color: '#9ddb22',
      cells: [
        { x: 0, y: 0 },
        { x: 1, y: 0 },
        { x: 2, y: 0 },
        { x: 2, y: 1 },
      ],
      count: 1,
    },
    {
      id: 'p-c',
      name: 'Step',
      color: '#9ddb22',
      cells: [
        { x: 1, y: 0 },
        { x: 2, y: 0 },
        { x: 0, y: 1 },
        { x: 1, y: 1 },
      ],
      count: 1,
    },
    {
      id: 'p-d',
      name: 'Mini-L',
      color: '#9ddb22',
      cells: [
        { x: 0, y: 0 },
        { x: 0, y: 1 },
        { x: 1, y: 1 },
      ],
      count: 1,
    },
    {
      id: 'piece_5',
      name: 'Piece 5',
      color: '#9ddb22',
      cells: [
        { x: 1, y: 0 },
        { x: 0, y: 1 },
        { x: 1, y: 1 },
        { x: 1, y: 2 },
        { x: 0, y: 2 },
        { x: 2, y: 0 },
      ],
      count: 1,
    },
    {
      id: 'piece_6',
      name: 'Piece 6',
      color: '#9ddb22',
      cells: [
        { x: 2, y: 0 },
        { x: 1, y: 0 },
        { x: 2, y: 1 },
        { x: 1, y: 1 },
        { x: 1, y: 2 },
        { x: 0, y: 2 },
      ],
      count: 1,
    },
  ],
};

export function cloneLevel(level: PuzzleLevelDefinition): PuzzleLevelDefinition {
  return {
    ...level,
    blocked: level.blocked.map((c) => ({ ...c })),
    hintCells: (level.hintCells ?? []).map((c) => ({ ...c })),
    ...(level.hintColors ? { hintColors: { ...level.hintColors } } : {}),
    rowTargets: [...level.rowTargets],
    colTargets: [...level.colTargets],
    ...(level.colorWeights ? { colorWeights: { ...level.colorWeights } } : {}),
    pieces: level.pieces.map((p) => ({
      ...p,
      count: p.count ?? 1,
      cells: p.cells.map((c) => ({ ...c })),
    })),
    ...(level.fixedPlacements
      ? {
          fixedPlacements: level.fixedPlacements.map((fixed) => ({
            ...fixed,
            anchor: { ...fixed.anchor },
            cells: fixed.cells.map((c) => ({ ...c })),
          })),
        }
      : {}),
  };
}
